AWSTemplateFormatVersion: "2010-09-09"
Description: App mesh definitions

Parameters:
  EnvironmentName:
    Type: String
    Default: prod
    Description: "A name that will be used for namespacing our cluster resources."

Resources:
  AppMesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub ${EnvironmentName}-appmesh
      Spec:
        EgressFilter:
          Type: "ALLOW_ALL"

Outputs:
  MeshName:
    Description: Name of the Mesh App
    Value:
      Fn::GetAtt:
        - AppMesh
        - MeshName
    Export:
      Name: !Sub ${EnvironmentName}-AppMeshName
  MeshCloudMapNamespace:
    Description: Namespace for mesh
    Value: !Sub ecs.${EnvironmentName}
    Export:
      Name: !Sub ${EnvironmentName}-MeshCloudMapNamespace
