version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=francisco
      - POSTGRES_PASSWORD=francisco
      - POSTGRES_DB=fiktionMaps
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    container_name: postgres